type: object
properties:
  auto_patch:
    description: Enable or Disable automatic execution of the policy.
    type: boolean
  auto_reboot:
    description: Enable or Disable automatic reboots following policy execution.
    type: boolean
  patch_rule:
    description: Use only with Patch policy.
    type: string
    default: filter
    enum:
      - all
      - filter
      - manual
      - advanced
    x-enumDescriptions:
      all: Patch All
      filter: Patch All Except or Patch Only or Patch by Severity
      manual: Manually Approve
      advanced: Advanced Patch Policy
  filter_type:
    description: Use only with `patch_rule` of `filter`
    type: string
    enum:
      - include
      - exclude
      - severity
    x-enumDescriptions:
      exclude: Patch All Except
      include: Patch Only
      severity: Patch by Severity
  filters:
    description: >-
      Define packages to filter on. Use with `patch_rule` of `filter` and
      `filter_type` of `include` or `exclude`
    type: array
    items:
      type: string
  device_filters_enabled:
    description: Enable or disable Device Filters.
    type: boolean
    default: false
  device_filters:
    $ref: ./DeviceFilters.yaml
  secrets:
    description: >-
      This object can optionally contain multiple objects containing information
      about secrets associated with the policy.
    type: object
    patternProperties:
      ^[a-zA-Z][a-zA-Z0-9_]+:
        type: object
        properties:
          id:
            type: string
            format: uuid
          organizationId:
            type: string
            format: uuid
          name:
            type: string
          description:
            type: string
          numPolicies:
            type: integer
          createdAt:
            type: string
            format: date-time
  severity_filter:
    description: Use only where `filter_type` is `severity`
    type:
      - array
      - 'null'
    items:
      type: string
      enum:
        - no_known_cves
        - none
        - unknown
        - low
        - medium
        - high
        - critical
  notify_reboot_user:
    description: >-
      Display modified notification 15 minutes before patching. This message
      should inform the user that a reboot will follow patching actions.
    type: boolean
  notify_deferred_reboot_user:
    description: >-
      If `true`, this shows a post-install reboot notification message, if
      `notify_reboot_deferred` is also `true`. If `notify_reboot_deferred` is
      `false` or `null`, this will sync with the existing `notify_reboot_user`
      parameter.
    type:
      - boolean
      - 'null'
  custom_notification_max_delays:
    description: Number of deferral chances before patching is forced.
    type: integer
    format: int64
  custom_notification_patch_message:
    description: >-
      Message to display before a non-rebooting patch policy executes on a
      Windows device. Maximum 125 characters
    type: string
    maxLength: 125
  custom_notification_reboot_message:
    description: >-
      Message to display before a rebooting patch policy executes on a Windows
      device. Reboot will follow patching actions. Maximum 125 characters
    type: string
    maxLength: 125
  custom_notification_deferment_periods:
    description: >-
      Integer array: Deferral time periods (hours) that users can choose from.
      Include up to 3. All 3 must be distinct with a maximum of 24
    type: array
    items:
      type: integer
    default:
      - 1
      - 4
      - 8
  custom_notification_patch_message_mac:
    description: >-
      Message to display before a non-rebooting patch policy executes on a macOS
      device. Maximum 70 characters
    type: string
    maxLength: 70
  custom_notification_reboot_message_mac:
    description: >-
      The custom reboot message for macOS, which overrides
      `custom_pending_reboot_notification_message` string, if provided.
    type: string
    maxLength: 70
  custom_pending_reboot_notification_message:
    description: Custom reboot message.
    type: string
    maxLength: 125
  notify_user_message_timeout:
    description: >-
      The amount of time a patch notification appears before timing out and
      closing. Min: 15 min. Max: 480 min. Default is 15 minutes.
    type: integer
    default: 15
    maximum: 480
    minimum: 15
  notify_user_auto_deferral_enabled:
    description: >-
      If a patch notification times out, apply the highest configured patch
      deferral.
    type: boolean
  notify_deferred_reboot_user_message_timeout:
    description: >-
      The amount of time a deferrable reboot notification message appears before
      timing out and closing. Min: 15 min. Max: 480 min. Default is 15 minutes.
    type: integer
    default: 15
    maximum: 480
    minimum: 15
  notify_deferred_reboot_user_auto_deferral_enabled:
    description: >-
      If a reboot notification times out, apply the highest configured reboot
      deferral.
    type: boolean
  custom_pending_reboot_notification_max_delays:
    description: >-
      Maximum number of times a user is allowed to defer the reboot. The default
      is 0.
    type: integer
    format: int64
    default: 0
  custom_pending_reboot_notification_message_mac:
    description: >-
      Message to display before a rebooting patch policy executes on a macOS
      device. Reboot will follow patching actions. Maximum 70 characters
    type: string
    maxLength: 70
  custom_pending_reboot_notification_deferment_periods:
    description: >-
      The time period options available to defer a reboot for each deferral
      selection. Default values: 1, 4, 8
    type: array
    items:
      type: integer
    default:
      - 1
      - 4
      - 8
  use_scheduled_timezone:
    description: >-
      Determines whether to use UTC or the local time of the device for policy
      execution. `true` = policy executes at the scheduled time in UTC, `false` =
      policy executes at the scheduled time using the device's local time.
    type: boolean
required:
  - auto_patch
  - patch_rule
  - auto_reboot
