type: object
properties:
  device_filters_enabled:
    description: Enable or disable Device Filters.
    type: boolean
    default: false
  device_filters:
    $ref: ./DeviceFilters.yaml
  secrets:
    description: >-
      This object can optionally contain multiple objects containing information
      about secrets associated with the policy.
    type: object
    patternProperties:
      ^[a-zA-Z][a-zA-Z0-9_]+:
        type: object
        properties:
          id:
            type: string
            format: uuid
          organizationId:
            type: string
            format: uuid
          name:
            type: string
          description:
            type: string
          numPolicies:
            type: integer
          createdAt:
            type: string
            format: date-time
  missed_patch_window:
    description: Enable or Disable Missed Patch Window setting
    type: boolean
  os_family:
    type: string
  package_name:
    type: string
  package_version:
    type: string
  installation_code:
    type: string
  use_scheduled_timezone:
    description: >-
      Determines whether to use UTC or the local time of the device for policy
      execution. `true` = policy executes at the scheduled time in UTC, `false`
      = policy executes at the scheduled time in the local time of the device.
    type: boolean
required:
  - package_name
  - package_version
  - installation_code
