type:
  - object
  - 'null'
properties:
  id:
    type: integer
    format: int64
  server_group_id:
    type: integer
    format: int64
  is_managed:
    type:
      - boolean
      - 'null'
  server_url:
    type:
      - string
      - 'null'
  created_at:
    type: string
  updated_at:
    type: string
