openapi: 3.0.3
info:
  title: Automox Remote Control Module API
  description: API for use with the Automox Remote Control module
  version: '2025-03-14_TEST'
  contact:
    name: Automox Support
    email: support@automox.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: https://rc.automox.com/api
security:
  - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
paths:
  /config/consent/account/:accountUuid/org/:orgUuid/device:
    $ref: paths/config_consent_account_:accountUuid_org_:orgUuid_device.yaml
